### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by HongboTang** [schneebergerlab/syri#109]
The following condition occurs when I run syri. Here is my command and error message. Looking forward to receiving your reply, thank you very much!
(syri) [root@Centos7 1.Mummer_rc01_align]# syri -c DU_WD_m4BETA_re.delta.coords -d DU_WD_m4BETA_re.delta -r DU2.0_FINAL_re.fa -q WD1.0_FINAL_re.fa
Reading Coords - WARNING - Reference chromosome Chr10 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr10). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome Chr11 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr11). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome Chr15 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr15). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome Chr25 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr25). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome Chr28 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr28). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome Chr3 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr3). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome Chr4 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr4). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome Chr5 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr5). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome Chr6 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr6). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome Chr7 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr7). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome Chr8 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr8). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/SOFTS/Anaconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/SOFTS/Anaconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 754, in syri.pyxFiles.synsearchFunctions.syri
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/syri", line 250, in <module>
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 456, in syri.pyxFiles.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 457, in syri.pyxFiles.synsearchFunctions.startSyri
  File "/home/SOFTS/Anaconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/SOFTS/Anaconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: list index out of range

**Comment by mnshgl0110** [comment]
Duplicate https://github.com/schneebergerlab/syri/issues/48
