### ISSUE TITLE
ImportError pytz/dateutil

### ISSUE THREAD

**Issue by njm-data** [schneebergerlab/syri#130]
Hi! I have conda installed syri (verision 1.5.4) and I am getting this error when I try to run the program:
Traceback (most recent call last):
  File "/home/njmello/.conda/envs/syri_env/bin/syri", line 4, in <module>
    __import__('pkg_resources').run_script('syri==1.5.4', 'syri')
  File "/home/njmello/.conda/envs/syri_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/njmello/.conda/envs/syri_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/njmello/.conda/envs/syri_env/lib/python3.8/site-packages/syri-1.5.4-py3.8-linux-x86_64.egg/EGG-INFO/scripts/syri", line 6, in <module>
    main(sys.argv[1:])
  File "/home/njmello/.conda/envs/syri_env/lib/python3.8/site-packages/syri-1.5.4-py3.8-linux-x86_64.egg/syri/scripts/syri.py", line 305, in main
    syri(args)
  File "/home/njmello/.conda/envs/syri_env/lib/python3.8/site-packages/syri-1.5.4-py3.8-linux-x86_64.egg/syri/scripts/syri.py", line 112, in syri
    from syri.synsearchFunctions import readCoords
  File "syri/pyxFiles/synsearchFunctions.pyx", line 11, in init syri.synsearchFunctions
  File "/home/njmello/.conda/envs/syri_env/lib/python3.8/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
pytz: No module named 'pytz'
dateutil: No module named 'dateutil'

However, I do have pytz installed (version 2021.3), and python-dateutil  (2.8.2 ).

I'm using python 3.8.13. Please let me know if you need any more information, or if you have a fix. I've tried new environments and different versions of conda and no luck. Thank you!!

**Comment by mnshgl0110** [comment]
Syri do not import these modules directly. From the error message it seems
that they are being imported by pandas. Have you tried
reinstalling/updating pandas?
Also, does `import pandas` work in python console?

When you tried new environments, then did you install python/other-modules
before installing syri or installed syri directly? Maybe try creating a new
empty environment (without even installing python) and then install syri
directly.

Another alternative is to first install a newer version of python (3.9) and
then install syri.

If the issue is still there and you can import pandas but syri still isn't
working, then could you please share the latest conda version that you
tried, the commands you used to create the environment and install/check
syri, and the list of installed packages. I can then try to replicate this
issue.



बुध, 6 अप्रैल 2022, 2:47 am को Jade Mellor ***@***.***> ने
लिखा:

**Comment by njm-data** [comment]
I did a fresh installation on a local computer instead of on a cluster and it seems to have worked. Thank you!
