### ISSUE TITLE
Runtime Error: "TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type"

### ISSUE THREAD

**Issue by HaimAshk** [schneebergerlab/syri#133]
Hi,

Thanks for developing SyRI! I am trying to use it with an alignment produced by minimap2 and get the following error. It happens both for my assemblies as well as for the example provided. Could you please advise what could be the problem, and how to solve it? 

Many thanks for your help!
Haim

### The command:
```
minimap2 -ax asm5 --eqx refgenome qrygenome > out.sam
syri -c out.sam -r refgenome -q qrygenome -k -F S
```

### The error message:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Programs/miniconda3/envs/SyRI_v1.5.4/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Programs/miniconda3/envs/SyRI_v1.5.4/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 580, in syri.synsearchFunctions.syri
  File ".local/lib/python3.8/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File ".local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File ".local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 69, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File ".local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 322, in _homogenize
    val = sanitize_array(
  File ".local/lib/python3.8/site-packages/pandas/core/construction.py", line 465, in sanitize_array
    subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype)
  File ".local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1452, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Programs/miniconda3/envs/SyRI_v1.5.4/bin/syri", line 4, in <module>
    __import__('pkg_resources').run_script('syri==1.5.4', 'syri')
  File "/Programs/miniconda3/envs/SyRI_v1.5.4/lib/python3.8/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Programs/miniconda3/envs/SyRI_v1.5.4/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/Programs/miniconda3/envs/SyRI_v1.5.4/lib/python3.8/site-packages/syri-1.5.4-py3.8-linux-x86_64.egg/EGG-INFO/scripts/syri", line 6, in <module>
    main(sys.argv[1:])
  File "/Programs/miniconda3/envs/SyRI_v1.5.4/lib/python3.8/site-packages/syri-1.5.4-py3.8-linux-x86_64.egg/syri/scripts/syri.py", line 320, in main
    syri(args)
  File "/Programs/miniconda3/envs/SyRI_v1.5.4/lib/python3.8/site-packages/syri-1.5.4-py3.8-linux-x86_64.egg/syri/scripts/syri.py", line 209, in syri
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 505, in syri.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 506, in syri.synsearchFunctions.startSyri
  File "/Programs/miniconda3/envs/SyRI_v1.5.4/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Programs/miniconda3/envs/SyRI_v1.5.4/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
```

### The syri log:
```
2022-04-19 17:37:02,012 - Reading Coords - INFO - syri:130 - Reading input from SAM file
2022-04-19 17:37:05,531 - syri - INFO - syri:209 - starting
2022-04-19 17:37:05,535 - syri - INFO - syri:209 - Analysing chromosomes: ['Chr1', 'Chr2', 'Chr3', 'Chr4', 'Chr5']
2022-04-19 17:37:05,555 - syri.Chr1 - INFO - mapstar:48 - Chr1 (1369, 11)
2022-04-19 17:37:05,555 - syri.Chr1 - INFO - mapstar:48 - Identifying Synteny for chromosome Chr1
2022-04-19 17:37:06,002 - syri.Chr1 - INFO - mapstar:48 - Identifying Inversions for chromosome Chr1
2022-04-19 17:37:06,211 - syri.Chr1 - INFO - mapstar:48 - Identifying translocation and duplication for chromosome Chr1
2022-04-19 17:37:06,225 - syri.Chr3 - INFO - mapstar:48 - Chr3 (911, 11)
2022-04-19 17:37:06,225 - syri.Chr3 - INFO - mapstar:48 - Identifying Synteny for chromosome Chr3
2022-04-19 17:37:06,456 - syri.Chr3 - INFO - mapstar:48 - Identifying Inversions for chromosome Chr3
2022-04-19 17:37:06,590 - syri.Chr3 - INFO - mapstar:48 - Identifying translocation and duplication for chromosome Chr3
2022-04-19 17:37:06,597 - syri.Chr5 - INFO - mapstar:48 - Chr5 (1191, 11)
2022-04-19 17:37:06,597 - syri.Chr5 - INFO - mapstar:48 - Identifying Synteny for chromosome Chr5
2022-04-19 17:37:06,905 - syri.Chr5 - INFO - mapstar:48 - Identifying Inversions for chromosome Chr5
2022-04-19 17:37:07,073 - syri.Chr5 - INFO - mapstar:48 - Identifying translocation and duplication for chromosome Chr5
```

### My conda enviorment:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
arpack                    3.7.0                hdefa2d7_2    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                 hf3e587d_9    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.3.29            h06a4308_0  
certifi                   2021.10.8        py38h578d9bd_2    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.23          py38h709712a_1    conda-forge
dbus                      1.13.18              hb2f20db_0  
expat                     2.4.8                h27087fc_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
freetype                  2.11.0               h70c0345_0  
gcc                       11.2.0               h702ea55_9    conda-forge
gcc_impl_linux-64         11.2.0              h82a94d6_15    conda-forge
gcc_linux-64              11.2.0               h39a9532_9    conda-forge
gettext                   0.21.0               hf68c758_0  
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.68.4               h9c3ff4c_0    conda-forge
glib-tools                2.68.4               h9c3ff4c_0    conda-forge
glpk                      4.65              h9202a9a_1004    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gst-plugins-base          1.18.5               hf529b03_0    conda-forge
gstreamer                 1.18.5               h76c114f_0    conda-forge
gxx_impl_linux-64         11.2.0              h82a94d6_15    conda-forge
gxx_linux-64              11.2.0               hacbe6df_9    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9e                   h166bdaf_1    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
kiwisolver                1.4.2            py38h43d8883_1    conda-forge
krb5                      1.19.2               hac12032_0  
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0           14_linux64_openblas    conda-forge
libcblas                  3.9.0           14_linux64_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.82.0               h0b77cf5_0  
libdeflate                1.7                  h27cfd23_5  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-devel_linux-64     11.2.0              h0952999_15    conda-forge
libgcc-ng                 11.2.0              h1d223b6_15    conda-forge
libgfortran-ng            11.2.0              h69a702a_15    conda-forge
libgfortran5              11.2.0              h5c6108e_15    conda-forge
libglib                   2.68.4               h3e27bee_0    conda-forge
libgomp                   11.2.0              h1d223b6_15    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           14_linux64_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_3    conda-forge
libnghttp2                1.46.0               hce63b2e_0  
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.5                h27cfd23_1  
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.5                 hd57d9b9_1    conda-forge
libsanitizer              11.2.0              he4da1e4_15    conda-forge
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-devel_linux-64  11.2.0              h0952999_15    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_15    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
matplotlib                3.3.4            py38h578d9bd_0    conda-forge
matplotlib-base           3.3.4            py38h0efea84_0    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
mysql-common              8.0.28               haf5c9bc_4    conda-forge
mysql-libs                8.0.28               h28c427c_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nspr                      4.33                 h295c915_0  
nss                       3.77                 h2350873_0    conda-forge
numpy                     1.21.2           py38he2449b9_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1n               h166bdaf_0    conda-forge
pandas                    1.2.4            py38h2531618_0  
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    9.1.0            py38h0ee0e06_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
plotsr                    0.5.3              pyh5e36f6f_0    bioconda
psutil                    5.8.0            py38h27cfd23_1  
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py38h578d9bd_8    conda-forge
pyqt-impl                 5.12.3           py38h0ffb2e6_8    conda-forge
pyqt5-sip                 4.19.18          py38h709712a_8    conda-forge
pyqtchart                 5.12             py38h7400c14_8    conda-forge
pyqtwebengine             5.12.1           py38h7400c14_8    conda-forge
pysam                     0.16.0.1         py38hf7546f9_3    bioconda
python                    3.8.13               h12debd9_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-igraph             0.9.1            py38h2af5540_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
readline                  8.1.2                h7f8727e_1  
scipy                     1.6.2            py38h7b17777_0    conda-forge
setuptools                62.1.0           py38h578d9bd_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.2               h4ff8645_0    conda-forge
suitesparse               5.10.1               h9e50725_1    conda-forge
syri                      1.5.4                    pypi_0    pypi
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tbb                       2021.5.0             h924138e_1    conda-forge
texttable                 1.6.4              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.1              py38h0a891b7_3    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

**Comment by mnshgl0110** [comment]
Hi Haim, I think the issue is with the conda environment. Have you tried creating a new conda environment and then installing syri there? I think, that would solve the issue.

**Comment by HaimAshk** [comment]
Thanks for the super quick response!
I have tried now with a new and clean conda environment and using the conda SyRI installation, but it failed. In the installation above I installed all the dependencies manually and use the python3 setup.py install with the source files from the git.

Any advice on how it can be solved?

## This is what I did now:
```
conda create -p /Programs/miniconda3/envs/SyRI_v1.5.4.test/ python=3.8
conda activate /Programs/miniconda3/envs/SyRI_v1.5.4.test
conda install -c bioconda syri 

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                                                                                                                                                                    

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0

Your installed version is: 2.27
```

**Comment by mnshgl0110** [comment]
Updating conda should help solve this issue: https://stackoverflow.com/questions/66888763/invalidversionspecerror-invalid-version-spec-2-7.

So something like:
```
conda create -p /Programs/miniconda3/envs/SyRI_v1.5.4.test/ python=3.8 conda
conda activate /Programs/miniconda3/envs/SyRI_v1.5.4.test
conda install -c bioconda syri 
```

should work.

**Comment by HaimAshk** [comment]
Thanks for the help, Manish!
Unfortunately, it still does not work 😢 

I managed to install it with the commands you suggested:

```
conda create -p /Programs/miniconda3/envs/SyRI_v1.5.4.test/ python=3.8 conda
conda activate /Programs/miniconda3/envs/SyRI_v1.5.4.test
conda install -c bioconda syri 
```
**But when running it, I still get the following runtime error:**

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Programs/miniconda3/envs/SyRI_v1.5.4.test/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Programs/miniconda3/envs/SyRI_v1.5.4.test/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 539, in syri.synsearchFunctions.syri
  File "syri/pyxFiles/tdfunc.pyx", line 1198, in syri.tdfunc.blocksdata
  File "syri/pyxFiles/tdfunc.pyx", line 304, in syri.tdfunc.mergeTransBlocks
  File "/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 490, in __init__
    mgr = init_dict({}, index, columns, dtype=dtype)
  File "/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1440, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Programs/miniconda3/envs/SyRI_v1.5.4.test/bin/syri", line 6, in <module>
    main(sys.argv[1:])
  File "/Programs/miniconda3/envs/SyRI_v1.5.4.test/lib/python3.8/site-packages/syri/scripts/syri.py", line 305, in main
    syri(args)
  File "/Programs/miniconda3/envs/SyRI_v1.5.4.test/lib/python3.8/site-packages/syri/scripts/syri.py", line 195, in syri
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 451, in syri.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 452, in syri.synsearchFunctions.startSyri
  File "/Programs/miniconda3/envs/SyRI_v1.5.4.test/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Programs/miniconda3/envs/SyRI_v1.5.4.test/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: type object 'object' has no attribute 'dtype'
```

## This is how the environment looks like:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
amply                     0.1.4                      py_0    conda-forge
arpack                    3.7.0                hdefa2d7_2    conda-forge
brotlipy                  0.7.0           py38h0a891b7_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.3.29            h06a4308_0  
certifi                   2021.10.8        py38h578d9bd_2    conda-forge
cffi                      1.15.0           py38h3931269_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
coin-or-cbc               2.10.7               h3786ebc_0    conda-forge
coin-or-cgl               0.60.3               he7e83c3_2    conda-forge
coin-or-clp               1.17.6               h256e9bb_3    conda-forge
coin-or-osi               0.108.6              h3b589db_2    conda-forge
coin-or-utils             2.11.6               h573740c_0    conda-forge
coincbc                   2.10.7            0_metapackage    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.12.0           py38h578d9bd_0    conda-forge
conda-package-handling    1.8.1            py38h0a891b7_1    conda-forge
cryptography              36.0.0           py38h9ce1e76_0  
docutils                  0.18.1           py38h578d9bd_1    conda-forge
glpk                      4.65              h9202a9a_1004    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           14_linux64_openblas    conda-forge
libcblas                  3.9.0           14_linux64_openblas    conda-forge
libcurl                   7.82.0               h7bff187_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_15    conda-forge
libgfortran-ng            11.2.0              h69a702a_15    conda-forge
libgfortran5              11.2.0              h5c6108e_15    conda-forge
libgomp                   11.2.0              h1d223b6_15    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           14_linux64_openblas    conda-forge
liblapacke                3.9.0           14_linux64_openblas    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_15    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.9.13               h22db469_0    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
longestrunsubsequence     1.0.1                      py_0    bioconda
metis                     5.1.0             h58526e2_1006    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.22.3           py38h1d589f8_2    conda-forge
openssl                   1.1.1n               h166bdaf_0    conda-forge
pandas                    1.4.2            py38h47df419_1    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
psutil                    5.9.0            py38h0a891b7_1    conda-forge
pulp                      2.6.0            py38h578d9bd_1    conda-forge
pycosat                   0.6.3           py38h0a891b7_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pysam                     0.19.0           py38h8bf8b8d_0    bioconda
pysocks                   1.7.1            py38h578d9bd_5    conda-forge
python                    3.8.13          h582c2e5_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-igraph             0.9.10           py38hb5c8105_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.100         py38h27cfd23_0  
scipy                     1.8.0            py38h56a6a73_1    conda-forge
setuptools                62.1.0           py38h578d9bd_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.2               h4ff8645_0    conda-forge
suitesparse               5.10.1               h9e50725_1    conda-forge
syri                      1.5.4            py38h3a7dea9_0    bioconda
tbb                       2021.5.0             h924138e_1    conda-forge
texttable                 1.6.4              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

**Comment by HaimAshk** [comment]
Just to update that I was able to fix the error with the solution provided here:
https://stackoverflow.com/questions/65998646/pandas-error-for-creating-an-emptydataframe

```
conda install -c conda-forge numpy==1.19.5
conda install -c conda-forge pandas==0.25.3
```

Many thanks for all the help!
Haim

**Comment by mnshgl0110** [comment]
Great that you made it work.

However, this solution depends on manually installing old versions of numpy and pandas. For future users, using
```
conda create -n syri_env -c bioconda syri
```
should install syri properly in a new environment.
