### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by hui-liu** [schneebergerlab/syri#16]
Hi,

The reference genome and the query genome has the same chromosome ids for homologous chromosomes and the number of chromosomes. I aligned them using minimap2, and called rearrangements using the following command:
```
$ python3 $PATH_TO_SYRI -c JGXP_WT18.bam -r JGXP.fasta -q WT18.fasta -k -F B --nosnp --nc 15 --prefix JGXP_WT18_
```
Then, I got the following issues:

```
Namespace(TransUniCount=1000, TransUniPercent=0.5, all=False, bruteRunTime=60, chrmatch=False, cigar=False, delta=None, dir=None, fout='syri', ftype='B', increaseBy=1000, infile=<_io.TextIOWrapper name='JGXP_WT18.bam' mode='r' encoding='UTF-8'>, keep=True, log='INFO', log_fin=<_io.TextIOWrapper name='syri.log' mode='w' encoding='UTF-8'>, nCores=15, nosnp=True, nosr=False, nosv=False, novcf=False, offset=5, prefix='JGXP_WT18_', qry=<_io.TextIOWrapper name='WT18.fasta' mode='r' encoding='UTF-8'>, ref=<_io.TextIOWrapper name='JGXP.fasta' mode='r' encoding='UTF-8'>, seed=1, sspath='show-snps')
syri - WARNING - starting
('Cluster is too big for Brute Force\nTime taken for last iteration ', 8.678436279296875e-05, ' iterations remaining ', 49)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 9.131431579589844e-05, ' iterations remaining ', 36)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 2.4318695068359375e-05, ' iterations remaining ', 45)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.00018978118896484375, ' iterations remaining ', 34)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.00010824203491210938, ' iterations remaining ', 33)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.001171112060546875, ' iterations remaining ', 46)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 6.556510925292969e-05, ' iterations remaining ', 34)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.0008320808410644531, ' iterations remaining ', 42)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.00020074844360351562, ' iterations remaining ', 41)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.00015544891357421875, ' iterations remaining ', 32)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.00010156631469726562, ' iterations remaining ', 36)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 4.76837158203125e-06, ' iterations remaining ', 46)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.000354766845703125, ' iterations remaining ', 39)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 1.2564423084259033, ' iterations remaining ', 10)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 6.699562072753906e-05, ' iterations remaining ', 34)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.0003211498260498047, ' iterations remaining ', 37)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 1.1444091796875e-05, ' iterations remaining ', 41)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/media/100TB/huli0009/bin/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/media/100TB/huli0009/bin/miniconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 623, in syri.pyxFiles.synsearchFunctions.syri
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/100TB/huli0009/bin/syri/syri/bin/syri", line 115, in <module>
    chrlink = startSyri(args)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 309, in syri.pyxFiles.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 310, in syri.pyxFiles.synsearchFunctions.startSyri
  File "/media/100TB/huli0009/bin/miniconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/media/100TB/huli0009/bin/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range
```
Here are what I got:
```
total 528K
-rw-rw-r-- 1 huli0009 huli0009  23K Nov 27 04:12 JGXP_ZS4_Chr01_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009    0 Nov 27 04:12 JGXP_ZS4_Chr01_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009  20K Nov 27 04:07 JGXP_ZS4_Chr02_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009    0 Nov 27 04:07 JGXP_ZS4_Chr02_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009  12K Nov 27 03:55 JGXP_ZS4_Chr03_dupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 5.3K Nov 27 03:55 JGXP_ZS4_Chr03_invDupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 1.2K Nov 27 03:55 JGXP_ZS4_Chr03_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009 5.8K Nov 27 03:55 JGXP_ZS4_Chr03_invTLOut.txt
-rw-rw-r-- 1 huli0009 huli0009  24K Nov 27 03:55 JGXP_ZS4_Chr03_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009 3.0K Nov 27 03:55 JGXP_ZS4_Chr03_TLOut.txt
-rw-rw-r-- 1 huli0009 huli0009 4.8K Nov 27 03:55 JGXP_ZS4_Chr04_dupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 3.1K Nov 27 03:55 JGXP_ZS4_Chr04_invDupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 4.8K Nov 27 03:55 JGXP_ZS4_Chr04_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009 4.8K Nov 27 03:55 JGXP_ZS4_Chr04_invTLOut.txt
-rw-rw-r-- 1 huli0009 huli0009  21K Nov 27 03:55 JGXP_ZS4_Chr04_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009 3.1K Nov 27 03:55 JGXP_ZS4_Chr04_TLOut.txt
-rw-rw-r-- 1 huli0009 huli0009 8.9K Nov 27 03:55 JGXP_ZS4_Chr05_dupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 4.3K Nov 27 03:55 JGXP_ZS4_Chr05_invDupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 2.0K Nov 27 03:55 JGXP_ZS4_Chr05_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009 3.5K Nov 27 03:55 JGXP_ZS4_Chr05_invTLOut.txt
-rw-rw-r-- 1 huli0009 huli0009  27K Nov 27 03:55 JGXP_ZS4_Chr05_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009 5.9K Nov 27 03:55 JGXP_ZS4_Chr05_TLOut.txt
-rw-rw-r-- 1 huli0009 huli0009  12K Nov 27 03:55 JGXP_ZS4_Chr06_dupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 6.2K Nov 27 03:55 JGXP_ZS4_Chr06_invDupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 3.2K Nov 27 03:55 JGXP_ZS4_Chr06_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009 4.7K Nov 27 03:55 JGXP_ZS4_Chr06_invTLOut.txt
-rw-rw-r-- 1 huli0009 huli0009  21K Nov 27 03:55 JGXP_ZS4_Chr06_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009 5.7K Nov 27 03:55 JGXP_ZS4_Chr06_TLOut.txt
-rw-rw-r-- 1 huli0009 huli0009  23K Nov 27 04:11 JGXP_ZS4_Chr07_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009    0 Nov 27 04:11 JGXP_ZS4_Chr07_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009 9.2K Nov 27 03:55 JGXP_ZS4_Chr08_dupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 6.0K Nov 27 03:55 JGXP_ZS4_Chr08_invDupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 2.1K Nov 27 03:55 JGXP_ZS4_Chr08_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009 5.0K Nov 27 03:55 JGXP_ZS4_Chr08_invTLOut.txt
-rw-rw-r-- 1 huli0009 huli0009  22K Nov 27 03:55 JGXP_ZS4_Chr08_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009 4.6K Nov 27 03:55 JGXP_ZS4_Chr08_TLOut.txt
-rw-rw-r-- 1 huli0009 huli0009  19K Nov 27 04:08 JGXP_ZS4_Chr09_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009    0 Nov 27 04:08 JGXP_ZS4_Chr09_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009  12K Nov 27 04:10 JGXP_ZS4_Chr10_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009    0 Nov 27 04:10 JGXP_ZS4_Chr10_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009 6.2K Nov 27 03:55 JGXP_ZS4_Chr11_dupOut.txt
-rw-rw-r-- 1 huli0009 huli0009 3.6K Nov 27 03:55 JGXP_ZS4_Chr11_invDupOut.txt
-rw-rw-r-- 1 huli0009 huli0009  778 Nov 27 03:55 JGXP_ZS4_Chr11_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009 4.7K Nov 27 03:55 JGXP_ZS4_Chr11_invTLOut.txt
-rw-rw-r-- 1 huli0009 huli0009  24K Nov 27 03:55 JGXP_ZS4_Chr11_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009 3.1K Nov 27 03:55 JGXP_ZS4_Chr11_TLOut.txt
-rw-rw-r-- 1 huli0009 huli0009  18K Nov 27 04:01 JGXP_ZS4_Chr12_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009    0 Nov 27 04:01 JGXP_ZS4_Chr12_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009  15K Nov 27 03:59 JGXP_ZS4_Chr13_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009    0 Nov 27 03:59 JGXP_ZS4_Chr13_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009  11K Nov 27 03:57 JGXP_ZS4_Chr14_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009    0 Nov 27 03:57 JGXP_ZS4_Chr14_synOut.txt
-rw-rw-r-- 1 huli0009 huli0009  18K Nov 27 04:09 JGXP_ZS4_Chr15_invOut.txt
-rw-rw-r-- 1 huli0009 huli0009    0 Nov 27 04:09 JGXP_ZS4_Chr15_synOut.txt
```

**Comment by mnshgl0110** [comment]
Hi,  thanks for sharing the details. It seems that you are using Python3.7. Can you please try it again with python 3.5? Some libraries have been changed between Python3.5 and 3.7 which sometimes result in unexpected errors. I would guess that using Python3.5 might be able to fix the problem.

**Comment by hui-liu** [comment]
Hi, thanks for replying. I got the same errors when using Python3.5.

**Comment by hui-liu** [comment]
Do you think the **whole chromosome inversion** can make such an issue?

**Comment by mnshgl0110** [comment]
Whole chromosome inversions is not a typical use case. So, it is possible that that there is some uncaught exception. From the output files, it indeed seems that for most chromosomes no syntenic region was identified. If this is indeed the problem, then you can easily solve this by reverse-complimenting the chromosomes for which no syntenic regions were found.

If the problem still persists, then it would be great to see the log file as well as a sample bam file (one chromosome) which can be used to reproduce this error.

**Comment by hui-liu** [comment]
Thanks. It works now after reverse-complementing the chromosomes with whole chromosome inversion.

I am wondering if I need to adjust the start/end for genome B in `syri.out`?

**Comment by mnshgl0110** [comment]
Hi. Good to know that it worked for you.
I would recommend that you reverse complement these "inverted" chromosomes in the fasta file itself. Then, you can do alignment and run SyRI again. This will ensure that the coordinates in ```syri.out``` are as per the reverse complemented chromosomes and would reduce chances of errors.

**Comment by hui-liu** [comment]
Thanks.
Yes, I did the same as you recommended.
Because the genomes I used to analyzed have been published, if I reverse complemented the original fasta files, the `syri.out` just record the coordinates of the reverse complemented chromosomes.

I think if I would like to get the coordinates of the original chromosomes, I should adjust the coordinates. Since I only reverse complemented the `genome B`, what I need to do is adjust the coordinates of chromosomes in `genome B`.

In my case, I would only summarize the rearrangements for the reference `genome A`. It would be OK whatever the coordinates of chromosomes in `genome B` like.

If people want to draw a local rearrangement between `genome A` and `genomeB`, I think they should use the coordinates from the original genome so that they can compare with the previous study. Do you think so?

**Comment by mnshgl0110** [comment]
It is not possible for me to comment on this.

You are correct in that the coordinates of the genome A would not change, and that you can reverse complement the coordinates from ```syri.out``` to get the original fasta file coordinates. However, it is upto you to decide how you want to report and represent this information :)
