### ISSUE TITLE
high fraction of inverted alignments 

### ISSUE THREAD

**Issue by YuChrming** [schneebergerlab/syri#163]
Good pipline to use easily! I met an error , how to solve it?
`syri -c out.sam -d out.best.delta -r HFTH1.all.chr.fa -q type03.fa -k -F S`

Reading Coords - WARNING - Reference chromosome Chr07 has high fraction of inverted alignments with its homologous chromosome in the query genome (Chr07). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/ngsproject/qmyu/miniconda3/envs/syri/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/ngsproject/qmyu/miniconda3/envs/syri/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 803, in syri.synsearchFunctions.syri
IndexError: list index out of range
"""

Thanks a lot!

**Comment by chhenyy** [comment]
I met the same error, 
syri -c out.sam -r chr15_1.fasta -q chr15_2.fasta -k -F S

Reading Coords - WARNING - Reference chromosome chr15 has high fraction of inverted alignments with its homologous chromosome in the query genome (chr15). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/UserHome/user/miniconda3/envs/syri/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/UserHome/user/miniconda3/envs/syri/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 803, in syri.synsearchFunctions.syri
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/UserHome/user/miniconda3/envs/syri/bin/syri", line 6, in <module>
    main(sys.argv[1:])
  File "/UserHome/user/miniconda3/envs/syri/lib/python3.8/site-packages/syri/scripts/syri.py                          ", line 319, in main
    syri(args)
  File "/UserHome/user/miniconda3/envs/syri/lib/python3.8/site-packages/syri/scripts/syri.py                          ", line 209, in syri
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir",                           "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 505, in syri.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 506, in syri.synsearchFunctions.startSyri
  File "/UserHome/user/miniconda3/envs/syri/lib/python3.8/multiprocessing/pool.py", line 364                          , in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/UserHome/user/miniconda3/envs/syri/lib/python3.8/multiprocessing/pool.py", line 771                          , in get
    raise self._value
IndexError: list index out of range

**Comment by mnshgl0110** [comment]
Please ensure that same strands are being compared for the homologous chromosomes. Check https://github.com/schneebergerlab/syri/issues/48
