### ISSUE TITLE
SNP Finding error 

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [schneebergerlab/syri#204]
Hi Dear Syri Team,
i am using your amazing tool.
But i am getting this error, if i put --nosnp then its work but i am interested to find SNP
I have also installed nucmer in syri_env.

(syri_env) padanas-MacBook-Pro:ID padana$ syri -c out.filtered.coords -d out.filtered.delta -r refgenome -q qrygenome
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - WARNING - Matching them automatically. For each reference genome, most similar query genome will be selected. Check mapids.txt for mapping used.
ctxOut.txt is empty. Skipping analysing it.
ctxOut.txt is empty. Skipping analysing it.
ctxOut.txt is empty. Skipping analysing it.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/padana/opt/anaconda3/envs/syri_env/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/padana/opt/anaconda3/envs/syri_env/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/findshv.pyx", line 108, in syri.findshv.getsnps
KeyError: 'chr1_IRGSP'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/padana/opt/anaconda3/envs/syri_env/bin/syri", line 6, in <module>
    main(sys.argv[1:])
  File "/Users/padana/opt/anaconda3/envs/syri_env/lib/python3.9/site-packages/syri/scripts/syri.py", line 326, in main
    syri(args)
  File "/Users/padana/opt/anaconda3/envs/syri_env/lib/python3.9/site-packages/syri/scripts/syri.py", line 252, in syri
    getshv(args, coords, chrlink)
  File "syri/pyxFiles/findshv.pyx", line 203, in syri.findshv.getshv
  File "syri/pyxFiles/findshv.pyx", line 204, in syri.findshv.getshv
  File "syri/pyxFiles/findshv.pyx", line 205, in syri.findshv.getshv
  File "/Users/padana/opt/anaconda3/envs/syri_env/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/padana/opt/anaconda3/envs/syri_env/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'chr1_IRGSP'

**Comment by mnshgl0110** [comment]
Please try running it in a new directory that only has the out.filtered.coords, out.filtered.delta, refgenome, qrygenome files.
