### ISSUE TITLE
i was using syri with two genome files its give me a error

### ISSUE THREAD

**Issue by Hemaprasanth24** [schneebergerlab/syri#208]
(py3.8) hemaprasanth@hemaprasanth-Aspire-A715-51G:~/main_syri/radiodurans_protealyticus$ syri -c r_pr.sam -r radiodurans.fasta -q protealyticus.fasta -k -F S --prefix r_pr
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - WARNING - Matching them automatically. For each reference genome, most similar query genome will be selected. Check mapids.txt for mapping used.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 803, in syri.synsearchFunctions.syri
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hemaprasanth/anaconda/envs/py3.8/bin/syri", line 6, in <module>
    main(sys.argv[1:])
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/syri/scripts/syri.py", line 326, in main
    syri(args)
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/syri/scripts/syri.py", line 214, in syri
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 505, in syri.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 506, in syri.synsearchFunctions.startSyri
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range

**Comment by mnshgl0110** [comment]
Duplicate https://github.com/schneebergerlab/syri/issues/154

**Comment by Hemaprasanth24** [comment]
Hii,
![gene_presence_absence_phylogeny](https://github.com/schneebergerlab/syri/assets/133568966/103e0f36-5f2d-4f8e-ad92-ef65cabc10f2)

as you mentioned above i just did the reverse complement of my query genome i got the out fie but i don't now is it correct 
because i have i phylogenetic tree based on gene presence and absence that shows the reference 
![r_p_c](https://github.com/schneebergerlab/syri/assets/133568966/ecf8be5c-8295-4d69-9595-80b70d62cfe8)
and  query genome are not closely related but the synteny plot from plotsr with this out file shows syntenic regions

**Comment by mnshgl0110** [comment]
Please start a separate issue for new questions.
