### ISSUE TITLE
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hrpelg** [schneebergerlab/syri#225]
Hi, 

I am getting this following error. Any ideas what is missing from my installation. I installed syri using conda

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/workspace/appscratch/miniconda/syri_env/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/workspace/appscratch/miniconda/syri_env/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 551, in syri.synsearchFunctions.syri
  File "syri/pyxFiles/inversions.pyx", line 584, in syri.inversions.getInversions
  File "syri/pyxFiles/inversions.pyx", line 98, in syri.inversions.getProfitable
  File "syri/pyxFiles/function.pxd", line 145, in syri.pyxFiles.function.getConnectivityGraph
  File "/workspace/appscratch/miniconda/syri_env/lib/python3.8/site-packages/igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory
 
Cheers

**Comment by mnshgl0110** [comment]
One of the syri's dependence (python-igraph) is not installed properly. Installing it should resolve the issue. Re-installing syri using conda would be the easiest solution.

**Comment by wrengs** [comment]
Hi Elena,

Adding to the previous comment.
Within your activated syri_env, use `conda install python-igraph`. This fixed the same error for me.

Cheers
