### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by pan-genome** [schneebergerlab/syri#25]
I got the following error when running syri:
/path/syri/bin/syri -c out_m_i90_l100.coords -r ref.fa -q query.fa -k -d out_m_i90_l100.delta

any idea? thank you!

syri - WARNING - starting
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 362, in syri.pyxFiles.synsearchFunctions.syri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 700, in syri.pyxFiles.synsearchFunctions.getSynPath
ValueError: max() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/syri/syri/bin/syri", line 115, in <module>
    chrlink = startSyri(args)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 311, in syri.pyxFiles.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 312, in syri.pyxFiles.synsearchFunctions.startSyri
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
ValueError: max() arg is an empty sequence

here is the log file: (looks like the error happens when it is calling translocation and dup in chr9 )
2020-03-10 13:47:56,650 - syri - WARNING - <module>:115 - starting
2020-03-10 13:47:56,653 - Reading Coords - INFO - <module>:115 - Reading input from .tsv file
2020-03-10 13:48:05,808 - syri - INFO - <module>:115 - Analysing chromosomes: ['Chr0', 'Chr1', 'Chr10', 'Chr2', 'Chr3', 'Chr4', 'Chr5', 'Chr6', 'Chr7', 'Chr8', 'Chr9']
2020-03-10 13:48:06,566 - syri.Chr0 - INFO - mapstar:44 - Chr0 (2065, 11)
2020-03-10 13:48:06,566 - syri.Chr0 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr0
2020-03-10 13:48:07,862 - syri.Chr0 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr0
2020-03-10 13:48:16,331 - syri.Chr0 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr0
2020-03-10 13:50:00,789 - syri.Chr1 - INFO - mapstar:44 - Chr1 (0, 11)
2020-03-10 13:50:00,789 - syri.Chr1 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr1
2020-03-10 13:50:01,213 - syri.Chr2 - INFO - mapstar:44 - Chr2 (9604, 11)
2020-03-10 13:50:01,214 - syri.Chr2 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr2
2020-03-10 13:50:19,335 - syri.Chr2 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr2
2020-03-10 15:27:50,313 - syri.Chr2 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr2
2020-03-10 15:36:56,381 - syri.Chr3 - INFO - mapstar:44 - Chr3 (9780, 11)
2020-03-10 15:36:56,383 - syri.Chr3 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr3
2020-03-10 15:37:15,246 - syri.Chr3 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr3
2020-03-10 15:42:05,687 - syri.Chr3 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr3
2020-03-10 15:49:06,173 - syri.Chr4 - INFO - mapstar:44 - Chr4 (9463, 11)
2020-03-10 15:49:06,177 - syri.Chr4 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr4
2020-03-10 15:49:21,402 - syri.Chr4 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr4
2020-03-10 15:52:07,506 - syri.Chr4 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr4
2020-03-10 15:58:20,288 - syri.Chr5 - INFO - mapstar:44 - Chr5 (8619, 11)
2020-03-10 15:58:20,288 - syri.Chr5 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr5
2020-03-10 15:58:33,046 - syri.Chr5 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr5
2020-03-10 16:00:35,611 - syri.Chr5 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr5
2020-03-10 16:06:40,948 - syri.Chr6 - INFO - mapstar:44 - Chr6 (7187, 11)
2020-03-10 16:06:40,949 - syri.Chr6 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr6
2020-03-10 16:06:49,995 - syri.Chr6 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr6
2020-03-10 16:07:57,365 - syri.Chr6 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr6
2020-03-10 16:15:09,059 - syri.Chr7 - INFO - mapstar:44 - Chr7 (7592, 11)
2020-03-10 16:15:09,059 - syri.Chr7 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr7
2020-03-10 16:15:18,045 - syri.Chr7 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr7
2020-03-10 16:16:42,809 - syri.Chr7 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr7
2020-03-10 16:22:03,063 - syri.Chr8 - INFO - mapstar:44 - Chr8 (6974, 11)
2020-03-10 16:22:03,063 - syri.Chr8 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr8
2020-03-10 16:22:10,781 - syri.Chr8 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr8
2020-03-10 16:23:28,347 - syri.Chr8 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr8
2020-03-10 16:30:54,816 - syri.Chr9 - INFO - mapstar:44 - Chr9 (6378, 11)
2020-03-10 16:30:54,816 - syri.Chr9 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr9
2020-03-10 16:31:01,710 - syri.Chr9 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr9
2020-03-10 16:31:57,941 - syri.Chr9 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr9

**Comment by mnshgl0110** [comment]
The following is the problematic part. 
 2020-03-10 13:50:00,789 - syri.Chr1 - INFO - mapstar:44 - Chr1 (0, 11)

It seems that there is something with the input alignments as there is no forward alignment between the homologous Chr1's in the two genomes. Maybe an issue with the coords file? Maybe different strands are being considered resulting in only inverted alignments?

**Comment by pan-genome** [comment]
looks like the after the log time, the program continued running for 3 hours and the output for Chr1 looks good, 
2020-03-10 13:50:00,789 - syri.Chr1 - INFO - mapstar:44 - Chr1 (0, 11)

I have a different jobs that give a bus error:
syri - WARNING - starting
/home/ke1777/.lsbatch/1583871124.2827294: line 8: 24389 Bus error               /lsf/job_starter/screnv python3 /path/syri/bin/syri -c out_m_i90_l100_n.coords -r ref.fa -q query.fa -k -d out_m_i90_l100_n.delta

the log file looks like here:
$ cat syri.log
2020-03-10 15:12:17,188 - syri - WARNING - <module>:115 - starting
2020-03-10 15:12:17,192 - Reading Coords - INFO - <module>:115 - Reading input from .tsv file
2020-03-10 15:12:26,947 - syri - INFO - <module>:115 - Analysing chromosomes: ['Chr0', 'Chr1', 'Chr10', 'Chr2', 'Chr3', 'Chr4', 'Chr5', 'Chr6', 'Chr7', 'Chr8', 'Chr9']
2020-03-10 15:12:27,842 - syri.Chr0 - INFO - mapstar:44 - Chr0 (4196, 11)
2020-03-10 15:12:27,842 - syri.Chr0 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr0
2020-03-10 15:12:32,482 - syri.Chr0 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr0
2020-03-10 15:13:16,876 - syri.Chr0 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr0
2020-03-10 15:14:59,902 - syri.Chr1 - INFO - mapstar:44 - Chr1 (11515, 11)
2020-03-10 15:14:59,905 - syri.Chr1 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr1
2020-03-10 15:15:26,049 - syri.Chr1 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr1
2020-03-10 15:20:37,313 - syri.Chr1 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr1
2020-03-10 15:33:15,184 - syri.Chr10 - INFO - mapstar:44 - Chr10 (2523, 11)
2020-03-10 15:33:15,187 - syri.Chr10 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr10
2020-03-10 15:33:16,787 - syri.Chr10 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr10
2020-03-10 15:33:21,379 - syri.Chr10 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr10
2020-03-10 15:33:50,389 - syri.Chr2 - INFO - mapstar:44 - Chr2 (9911, 11)
2020-03-10 15:33:50,389 - syri.Chr2 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr2
2020-03-10 15:34:10,410 - syri.Chr2 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr2
2020-03-10 15:42:48,906 - syri.Chr2 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr2
2020-03-10 15:51:32,808 - syri.Chr3 - INFO - mapstar:44 - Chr3 (7163, 11)
2020-03-10 15:51:32,812 - syri.Chr3 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr3
2020-03-10 15:51:42,275 - syri.Chr3 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr3
2020-03-10 15:52:59,599 - syri.Chr3 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr3
2020-03-10 15:59:00,235 - syri.Chr4 - INFO - mapstar:44 - Chr4 (5532, 11)
2020-03-10 15:59:00,238 - syri.Chr4 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr4
2020-03-10 15:59:06,081 - syri.Chr4 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr4
2020-03-10 15:59:46,327 - syri.Chr4 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr4
2020-03-10 16:02:47,277 - syri.Chr5 - INFO - mapstar:44 - Chr5 (7170, 11)
2020-03-10 16:02:47,277 - syri.Chr5 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr5
2020-03-10 16:02:56,320 - syri.Chr5 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr5
2020-03-10 16:04:10,159 - syri.Chr5 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr5
2020-03-10 16:08:51,449 - syri.Chr6 - INFO - mapstar:44 - Chr6 (5851, 11)
2020-03-10 16:08:51,449 - syri.Chr6 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr6
2020-03-10 16:08:57,735 - syri.Chr6 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr6
2020-03-10 16:09:38,643 - syri.Chr6 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr6
2020-03-10 16:12:18,600 - syri.Chr7 - INFO - mapstar:44 - Chr7 (4056, 11)
2020-03-10 16:12:18,604 - syri.Chr7 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr7
2020-03-10 16:12:21,842 - syri.Chr7 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr7
2020-03-10 16:12:37,770 - syri.Chr7 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr7
2020-03-10 16:14:32,971 - syri.Chr8 - INFO - mapstar:44 - Chr8 (5153, 11)
2020-03-10 16:14:32,972 - syri.Chr8 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr8
2020-03-10 16:14:38,011 - syri.Chr8 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr8
2020-03-10 16:15:08,959 - syri.Chr8 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr8
2020-03-10 16:17:21,990 - syri.Chr9 - INFO - mapstar:44 - Chr9 (2432, 11)
2020-03-10 16:17:21,991 - syri.Chr9 - INFO - mapstar:44 - Identifying Synteny for chromosome Chr9
2020-03-10 16:17:23,416 - syri.Chr9 - INFO - mapstar:44 - Identifying Inversions for chromosome Chr9
2020-03-10 16:17:27,639 - syri.Chr9 - INFO - mapstar:44 - Identifying translocation and duplication for chromosome Chr9
2020-03-10 16:18:06,266 - getCTX - INFO - <module>:115 - Identifying cross-chromosomal translocation and duplication for chromosome

**Comment by mnshgl0110** [comment]
Bus error seems to be an LSF issue. Please check that.

**Comment by pan-genome** [comment]
Thanks! I will test it on local machine.

**Comment by mnshgl0110** [comment]
Let me know if this problem still persists.

**Comment by pan-genome** [comment]
It still failed on local machine, the process hung at the step:  getCTX - INFO - <module>:128 - Identifying cross-chromosomal translocation and duplication for chromosome

I put it on a high memory machine (r5.12xlarge) on EC2 and look it passed the failed step and still running for over 15 hours and I see it used a large amount of memory, btw the ref and query are maize genomes.
![image](https://user-images.githubusercontent.com/61593978/76625451-3c5a1580-6505-11ea-8185-0f5994919896.png)

**Comment by mnshgl0110** [comment]
Maize genomes are indeed quite tricky to work with, and SyRI could require more resources for such complicated genomes. In this particular case there are over 1.3Million alignments that can result in inter-chromosomal rearrangements, so that is a bit overwhelming for the algorithm.
This can be improved by changing the whole-genome alignment parameters to get longer alignments. Also, for maize, it might make sense to remove smaller alignments which predominantly consists of redundant TE alignments. Could you please share the command that you are using to align genomes? I might be able to suggest some changes.

**Comment by pan-genome** [comment]
Thank you.
The mapping used the following:
MUMmer3.23/nucmer --maxmatch -c 500 -b 500 -l 100 ref.fa query.fa
the filter used:
MUMmer3.23/delta-filter -m -i 90 -l 100

**Comment by pan-genome** [comment]
will it work if I directly filter the coords file on column 5 and column 6 to remove shorter alignments?

**Comment by mnshgl0110** [comment]
I would suggest to try with `delta-filter -m -i 90 -l 1000`. This will filter out all alignments that are smaller than 1000bps, and could substantially improve SyRI's performance. Additionally, you could also consider repeat masking the genomes to get rid of all repetitive genomes.

**Comment by pan-genome** [comment]
will it work if I directly filter the coords file on column 5 and column 6 to remove shorter alignments?

**Comment by mnshgl0110** [comment]
You can directly remove small alignments. I can't think of a reason which could lead to problems.

**Comment by pan-genome** [comment]
there are only 47621 (only about 3% of the 1531019 total) alignments that is shorter than 1000bp.  would it be useful to remove this 3%?

**Comment by mnshgl0110** [comment]
Removing 20% alignments would make it comparatively faster, but I assume that it would still take some time to process over 1mil alignments. Repeat masking could make a difference. Alternatively, you can compare individual chromosomes separately which would be quite fast, but this will not identify inter-chromosomal rearrangements.
Making tree is currently the major bottleneck in CTX identification, so once this step finishes then the rest would finish too. So there might be some merit in letting it run.

**Comment by pan-genome** [comment]
I assume we only need to do repeat masking on one genome e.g. ref.fa. not need to do masking on both genomes. or do you think otherwise?

**Comment by mnshgl0110** [comment]
For my analysis of maize genomes, I masked both genomes. I think that would be the safer option.

**Comment by pan-genome** [comment]
I did a test with a 3k size cutoff that filtered about 36% of the alignments, both the original job and the job with 3k cutoff are running over 70 hours and can not pass the tree making step. looks like the only option left for me is to mask genome.

**Comment by pan-genome** [comment]
got another error says:
syri - WARNING - starting
ShV - ERROR - Error in finding SNPs using show-snps: ERROR: One or more alignments from stdin could not be found

**Comment by mnshgl0110** [comment]
Hi. This error is given by show-snps (a utility from the [MUMmer ](http://mummer.sourceforge.net/manual/) package) and it is caused when it cannot find an alignment from the coords file in the delta file. This generally happens when the alignments in the coords file are manually changed.
Earlier, you mentioned about filtering out small alignments from the coords file? Are you using this filtered file now? I do not expect the removal of alignments from coords file to be problematic, but it could be possible that something else changed during that process. You can try running the show-snps utility directly to check whether it is accepting the coords file or not.
`cat <input_file_name>.coords | show-snps -STHr <input_file_name>.delta`
