### ISSUE TITLE
'Pandas' object has no attribute 'to_string'

### ISSUE THREAD

**Issue by luckynerwang** [schneebergerlab/syri#272]
**Describe the bug**
parsesvs - ERROR - Error in finding parent for SV
Traceback (most recent call last):
  File "/mnt/Data_disk/miniconda3/envs/py38/bin/syri", line 33, in <module>
    sys.exit(load_entry_point('syri==1.7.1', 'console_scripts', 'syri')())
  File "/mnt/Data_disk/miniconda3/envs/py38/lib/python3.8/site-packages/syri-1.7.1-py3.8-linux-x86_64.egg/syri/scripts/syri.py", line 328, in main
    syri(args)
  File "/mnt/Data_disk/miniconda3/envs/py38/lib/python3.8/site-packages/syri-1.7.1-py3.8-linux-x86_64.egg/syri/scripts/syri.py", line 267, in syri
    getTSV(args.dir, args.prefix, args.ref.name, args.hdrseq, args.maxs)
  File "syri/pyxFiles/writeout.pyx", line 400, in syri.writeout.getTSV
  File "syri/pyxFiles/writeout.pyx", line 146, in syri.writeout.parsesvs
AttributeError: 'Pandas' object has no attribute 'to_string'

2024-12-15 12:32:12,435 - Brute-force TD identification - INFO - mapstar:48 - Cl
uster is too big for Brute Force, using randomized-greedy approach
Time taken for last iteration 8.96453857421875e-05. iterations remaining 34
2024-12-15 12:32:37,791 - Brute-force TD identification - INFO - mapstar:48 - Cl
uster is too big for Brute Force, using randomized-greedy approach
Time taken for last iteration 0.000988006591796875. iterations remaining 29
2024-12-15 12:47:58,684 - Brute-force TD identification - INFO - mapstar:48 - Cl
uster is too big for Brute Force, using randomized-greedy approach
Time taken for last iteration 0.0012481212615966797. iterations remaining 29
2024-12-15 12:52:17,391 - getCTX - INFO - syri:215 - Identifying cross-chromosom
al translocation and duplication for chromosome2024-12-15 12:52:17.391070
2024-12-15 12:52:30,803 - local_variation - INFO - syri:226 - Finding SVs in syn
Out.txt, invOut.txt, TLOut.txt, invTLOut.txt, dupOut.txt, invDupOut.txt, ctxOut.
txt
2024-12-15 12:54:19,675 - local_variation - INFO - syri:246 - Finding SNPs and s
mall indels
2024-12-15 12:57:58,898 - local_variation - INFO - syri:258 - Combining outputs
2024-12-15 12:57:58,899 - local_variation - INFO - syri:263 - Generating table o
utput
2024-12-15 12:58:58,888 - parsesvs - ERROR - syri:267 - Error in finding parent
for SV

Then I encountered the same error as mentioned above. I have checked and confirmed that my snps.txt file is fine. Additionally, I tried setting up new environments to run both syri version 1.4 and 1.7. In both cases, I installed the required corresponding software version, including pandas etc., following your instructions, and used python setup.py to install syri. However, I encountered the same error. The only issue is that the syri.out output for the final step is not generated for this particular chromosome 10, while the results for other chromosomes from the same individual are produced without issues. I have been puzzled by this for several days. I would greatly appreciate any help.

**Version**
 - Python 3.8.20
 - pandas 1.2.4
 - Cython 0.29.23

**Comment by luckynerwang** [comment]
I've sent it to your e-mail. Thank you very much for your help!!

**Comment by luckynerwang** [comment]
I have solved this problem, my suggestion is to refer to the example that others have written, conda create a new environment such as python 3.8.6, install pandas with pip, etc., then reduce invgaplen, tdgaplen, tdmaxolp, add --unic, and moreover with the help of --log DEBUG, which shows this very clearly. and -unic, and --log DEBUG, which will clearly document where it got stuck. Many thanks to the developers for their help!

**Comment by luckynerwang** [comment]
I have solved this problem, my suggestion is to refer to the examples written by others, conda create a new environment like python 3.8.6, install pandas etc. with pip and reduce invgaplen, tdgaplen, tdmaxolp and increase --unic and with the help of the --log DEBUG, it will show this very clearly. Many thanks to the developers for their help!
