### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by song984888** [schneebergerlab/syri#28]
hi, these error reported, would you help me ? thank you!
error log:

syri — WARNING — starting
/data/home/songht/tools/SyRI/syri/syri/bin/syri:106: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  chrlink = startSyri(args)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/software/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/data/software/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 260, in syri.pyxFiles.synsearchFunctions.syri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 598, in syri.pyxFiles.synsearchFunctions.getSynPath
ValueError: max() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/songht/tools/SyRI/syri/syri/bin/syri", line 106, in <module>
    chrlink = startSyri(args)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 209, in syri.pyxFiles.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 210, in syri.pyxFiles.synsearchFunctions.startSyri
  File "/data/software/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/data/software/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: max() arg is an empty sequence

**Comment by mnshgl0110** [comment]
Hi, Could you please run SyRI with Python version 3.5.6 with pandas version 0.23.4. Newer version of pandas result in this warning `FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.` which can cause such errors.
Also, please check that for homologous chromosomes same strands are being analysed. As analysing different strands results in the entire chromosome being annotated as inversion which can result in such bugs.
If the problem still persists then can you please run SyRI with `--log DEBUG` and share the syri.log file.
