### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dej-deng** [schneebergerlab/syri#31]
hello，
I run syri on a big genome with ～4g size and 7 chromosomes, than get a error message:

syri - WARNING - starting
/share/nas2/genome/biosoft/syri/1.1/syri/bin/syri:115: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  chrlink = startSyri(args)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/Python/3.5.2/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/share/nas2/genome/biosoft/Python/3.5.2/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 622, in syri.pyxFiles.synsearchFunctions.syri
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/syri/1.1/syri/bin/syri", line 115, in <module>
    chrlink = startSyri(args)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 308, in syri.pyxFiles.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 309, in syri.pyxFiles.synsearchFunctions.startSyri
  File "/share/nas2/genome/biosoft/Python/3.5.2/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/share/nas2/genome/biosoft/Python/3.5.2/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
IndexError: list index out of range

How can I sovle this problem ?
Thanks!

**Comment by mnshgl0110** [comment]
Hi. Could you please check what version of pandas are you using? SyRI works with pandas version 0.23.4 and the newer versions of pandas are known to result in such errors.

**Comment by dej-deng** [comment]
> Hi. Could you please check what version of pandas are you using? SyRI works with pandas version 0.23.4 and the newer versions of pandas are known to result in such errors.

Thanks，the pandas version I used is 0.24.2. I will try using 0.23.4.
