### ISSUE TITLE
TypeError: unorderable types: str() > int()

### ISSUE THREAD

**Issue by giancarloRussoFGCZ** [schneebergerlab/syri#45]
Hi guys, 

thanks for Syri. However I have troubles using it. Here the full error:

```
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ python $syriExec -c refGenome.vs.qryGenome.bam  -r $refGenome -q $qryGenome -k -F B
Traceback (most recent call last):
  File "/usr/local/ngseq/src/syri/syri/bin/syri", line 163, in <module>
    coords, chrlink = readCoords(args.infile.name, args.chrmatch, args.dir, args.prefix, args, args.cigar)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 253, in syri.pyxFiles.synsearchFunctions.readCoords
  File "/usr/local/ngseq/miniconda3/envs/py35/lib/python3.5/site-packages/pandas/core/ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "/usr/local/ngseq/miniconda3/envs/py35/lib/python3.5/site-packages/pandas/core/ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "/usr/local/ngseq/miniconda3/envs/py35/lib/python3.5/site-packages/pandas/core/ops.py", line 1122, in _comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 98, in pandas._libs.ops.scalar_compare
TypeError: unorderable types: str() > int()

```

Here is the  executable seeming to work OK

```
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ echo $syriExec
/usr/local/ngseq/src/syri/syri/bin/syri
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ python $syriExec -h
usage: syri [-h] -c INFILE [-r REF] [-q QRY] [-d DELTA] [-F {T,S,B}] [-k]
            [--log {DEBUG,INFO,WARN}] [--lf LOG_FIN] [--dir DIR]
            [--prefix PREFIX] [--seed SEED] [--nc NCORES] [--novcf] [-f]
            [--nosr] [--tdgaplen TDGL] [-b BRUTERUNTIME]
            [--unic TRANSUNICOUNT] [--unip TRANSUNIPERCENT] [--inc INCREASEBY]
            [--no-chrmatch] [--nosv] [--nosnp] [--all] [--allow-offset OFFSET]
            [--cigar] [-s SSPATH]

Input Files:
  -c INFILE             File containing alignment coordinates (default: None)
  -r REF                Genome A (which is considered as reference for the
                        alignments). Required for local variation (large
                        indels, CNVs) identification. (default: None)
  -q QRY                Genome B (which is considered as query for the
                        alignments). Required for local variation (large
                        indels, CNVs) identification. (default: None)
  -d DELTA              .delta file from mummer. Required for short variation
                        (SNPs/indels) identification when CIGAR string is not
                        available (default: None)

optional arguments:
  -h, --help            show this help message and exit
  -F {T,S,B}            Input file type. T: Table, S: SAM, B: BAM (default: T)
  -k                    Keep intermediate output files (default: False)
  --log {DEBUG,INFO,WARN}
                        log level (default: INFO)
  --lf LOG_FIN          Name of log file (default: syri.log)
  --dir DIR             path to working directory (if not current directory).
                        All files must be in this directory. (default: None)
  --prefix PREFIX       Prefix to add before the output file Names (default: )
  --seed SEED           seed for generating random numbers (default: 1)
  --nc NCORES           number of cores to use in parallel (max is number of
                        chromosomes) (default: 1)
  --novcf               Do not combine all files into one output file
                        (default: False)
  -f                    Filter out low quality alignments (default: True)

SR identification:
  --nosr                Set to skip structural rearrangement identification
                        (default: False)
  --tdgaplen TDGL       Maximum allowed gap-length between two alignments of a
                        multi-alignment translocation or duplication (TD).
                        Larger values increases TD identification sensitivity
                        but also runtime. (default: 500000)
  -b BRUTERUNTIME       Cutoff to restrict brute force methods to take too
                        much time (in seconds). Smaller values would make
                        algorithm faster, but could have marginal effects on
                        accuracy. In general case, would not be required.
                        (default: 60)
  --unic TRANSUNICOUNT  Number of uniques bps for selecting translocation.
                        Smaller values would select smaller TLs better, but
                        may increase time and decrease accuracy. (default:
                        1000)
  --unip TRANSUNIPERCENT
                        Percent of unique region requried to select
                        translocation. Value should be in range (0,1]. Smaller
                        values would selection of translocation which are more
                        overlapped with other regions. (default: 0.5)
  --inc INCREASEBY      Minimum score increase required to add another
                        alignment to translocation cluster solution (default:
                        1000)
  --no-chrmatch         Do not allow SyRI to automatically match chromosome
                        ids between the two genomes if they are not equal
                        (default: False)

ShV identification:
  --nosv                Set to skip structural variation identification
                        (default: False)
  --nosnp               Set to skip SNP/Indel (within alignment)
                        identification (default: False)
  --all                 Use duplications too for variant identification
                        (default: False)
  --allow-offset OFFSET
                        BPs allowed to overlap (default: 5)
  --cigar               Find SNPs/indels using CIGAR string. Necessary for
                        alignment generated using aligners other than nucmers
                        (default: False)
  -s SSPATH             path to show-snps from mummer (default: show-snps)
```

Here the dependencies

```
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ pip show Cython | grep Version 
Version: 0.28.2
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ pip show numpy | grep Version 
Version: 1.14.3
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ pip show scipy | grep Version 
Version: 1.1.0
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ pip show pandas | grep Version 
Version: 0.23.4
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ pip show  python-igraph | grep Version 
Version: 0.8.2
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ pip show  biopython | grep Version 
Version: 1.76
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ pip show  psutil| grep Version 
Version: 5.4.5
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ pip show  pysam| grep Version 
Version: 0.15.1
(py35) grusso@fgcz-h-105:/srv/GT/analysis/grusso/darioCopetti/syriResults$ pip show  matplotlib| grep Version 
Version: 2.2.2
```

It's a python 3.5 conda environment. 

What am I missing? 
Many thanks, 
Giancarlo

**Comment by giancarloRussoFGCZ** [comment]
Thanks a lot, it works well now, including the plots. I am closing the issue. Take care, 
Giancarlo
