### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lvbakker** [schneebergerlab/syri#48]
Hi,
I executed the following commands:

nucmer --maxmatch -c 100 -b 500 -l 500 -L 5000 refgenome qrygenome                                                                                                                  
delta-filter -m -i 90 -l 100 out.delta > out.filtered.delta                                                                                     
show-coords -THrd out.filtered.delta > out.filtered.coords
python3 ${PATH_TO_SYRI}syri --log DEBUG --no-chrmatch -c out.filtered.coords -d out.filtered.delta -r refgenome -q qrygenome

But after it runs for a while, i stops with this message:

"""
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.0/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/cm/shared/apps/python/3.5.0/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 655, in syri.pyxFiles.synsearchFunctions.syri (syri/pyxFiles/synsearchFunctions.cpp:22087)
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/scratch/WUR/PRI/bakke227/tools/syri/syri/bin/syri", line 216, in <module>
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 359, in syri.pyxFiles.synsearchFunctions.startSyri (syri/pyxFiles/synsearchFunctions.cpp:13110)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 360, in syri.pyxFiles.synsearchFunctions.startSyri (syri/pyxFiles/synsearchFunctions.cpp:13060)
  File "/cm/shared/apps/python/3.5.0/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/cm/shared/apps/python/3.5.0/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
IndexError: list index out of range

What can i do to solve this?

with kind regards,
Linda

**Comment by mnshgl0110** [comment]
Hi Linda. Can you please share the log file? Was there a warning message complaining about too many inverted alignments?

**Comment by lvbakker** [comment]
[syri.log](https://github.com/schneebergerlab/syri/files/5369625/syri.log)

Syri.log states this indeed. How can i resolve this?

**Comment by mnshgl0110** [comment]
That means that potentially your assemblies have different strands for that chromosome. Reverse complement the chromosome/s (for which you get this warning) and try again. This is described in more detail in the README.

**Comment by lvbakker** [comment]
Hi, I did the reverse complement for all contigs mentioned in the log file, but after i ran nucmer and syri again, i still get the same message for 4 of the contigs. So changing to the reverse complement did not work for these 4. What can i additionally try? For the other contigs it shows output.

**Comment by mnshgl0110** [comment]
The basic assumption with syri is that the compared sequences would be homologous to each other, i.e. they would be largely syntenic. Since, these four contigs did not work in both cases, I suspect that they might not be homologous. You could check if that is the case with these four contigs.

If the compared sequences are not homologous, then syntenic region cannot be identified and as a result syri cannot work.

Additionally, comparing highly divergent sequences would not result in biologically relevant structural rearrangements anyway.

**Comment by lvbakker** [comment]
Hi,
I removed the most conflicting contigs and now i am left with this error:

Traceback (most recent call last):
  File "/lustre/scratch/WUR/PRI/bakke227/tools/syri/syri/bin/syri", line 216, in <module>
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 367, in syri.pyxFiles.synsearchFunctions.startSyri (syri/pyxFiles/synsearchFunctions.cpp:13271)
  File "syri/pyxFiles/tdfunc.pyx", line 511, in syri.pyxFiles.tdfunc.getCTX (syri/pyxFiles/tdfunc.cpp:16911)
  File "syri/pyxFiles/tdfunc.pyx", line 447, in syri.pyxFiles.tdfunc.readAnnoCoords (syri/pyxFiles/tdfunc.cpp:14839)
ValueError: invalid literal for int() with base 10: '14270551.0'
(END)

How can i solve this?
thanks for your help.

[syri_22okt.log](https://github.com/schneebergerlab/syri/files/5422004/syri_22okt.log)

**Comment by mnshgl0110** [comment]
Hi Linda. The log file contains a warning that the pandas version is 0.18.0. SyRI was designed using pandas version 0.23.4. I guess, that this might have caused this problem. Please check the installation guide [here](https://schneebergerlab.github.io/syri/install.html). Upgrading pandas (and then reinstalling SyRI) might solve this issue.

Other than this, I do not see any obvious reason for this error in the current log file. If the problem persists after upgrading pandas, than could you please run SyRI with DEBUG mode of logging and then share the new log file.
