### ISSUE TITLE
chroder MemoryError

### ISSUE THREAD

**Issue by jinshangkun** [schneebergerlab/syri#49]
Hi! I got a MemoryError error when I was running chroder, How can I solve it? Thank you！
The following is the error log：
Traceback (most recent call last):
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 732, in <module>
    scaf(args)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 340, in scaf
    refdata = getdata(reflength, refid, refdir)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 144, in getdata
    path = getpath(nodes)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 34, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 50, in getpath
    path = path + getpath(nodes, added, nodes[i].children[0], last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 50, in getpath
    path = path + getpath(nodes, added, nodes[i].children[0], last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 50, in getpath
    path = path + getpath(nodes, added, nodes[i].children[0], last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 50, in getpath
    path = path + getpath(nodes, added, nodes[i].children[0], last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 62, in getpath
    tmppath = getpath(nodes, added, j, last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 50, in getpath
    path = path + getpath(nodes, added, nodes[i].children[0], last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 50, in getpath
    path = path + getpath(nodes, added, nodes[i].children[0], last)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 64, in getpath
    tmppath = getpath(nodes, added + [nodes[i].name], j, nodes[i].name)
  File "/public/home/zhangtz/user/jsk/tools/syri-master/syri/bin/chroder", line 54, in getpath
    path = path + getpath(nodes, added + [nodes[i].name], nodes[i].children[0], nodes[i].name)
MemoryError

**Comment by mnshgl0110** [comment]
Hi. The script ran out of memory, adding more memory should fix this. Alternatively, remove small contigs and contigs consisting of repetitive sequence.

**Comment by jinshangkun** [comment]
Thank you for your reply！Could you tell me how to add more memory? I don't know where to add parameters。

**Comment by mnshgl0110** [comment]
To add more memory, you would just need to run it on a machine with more memory. This is a problem of the current heuristics where in some cases the amount of required memory increases significantly, which makes the script rather useless.

So, I would guess that the more pragmatic solution would be to try using it with a smaller number of only large contigs.

**Comment by jinshangkun** [comment]
OK！I get it，Thanks again！

**Comment by mnshgl0110** [comment]
The chroder script now uses the string clustering [algorithm](https://drops.dagstuhl.de/opus/volltexte/2020/12795/) developed in Gunnar Klau's lab and is now much more memory efficient.

This should resolve this issue with most of the practical cases.
