### ISSUE TITLE
Python ImportError

### ISSUE THREAD

**Issue by zbyxinalice03** [schneebergerlab/syri#68]
Hi:
   Thanks for your contribution for the usage of this program. It is my start to learn syRI. I met an error when I run syri/bin/syri:
Traceback (most recent call last):
  File "/home/zhuby/soft/syri/syri/bin/syri", line 165, in <module>
    from syri.pyxFiles.synsearchFunctions import readCoords
  File "syri/pyxFiles/synsearchFunctions.pyx", line 11, in init syri.pyxFiles.synsearchFunctions
  File "/home/zhuby/soft/install_path/envs/syri/lib/python3.5/site-packages/scipy/__init__.py", line 156, in <module>
    from . import fft
  File "/home/zhuby/soft/install_path/envs/syri/lib/python3.5/site-packages/scipy/fft/__init__.py", line 76, in <module>
    from ._basic import (
  File "/home/zhuby/soft/install_path/envs/syri/lib/python3.5/site-packages/scipy/fft/_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "/home/zhuby/soft/install_path/envs/syri/lib/python3.5/site-packages/scipy/_lib/uarray.py", line 27, in <module>
    from ._uarray import *
  File "/home/zhuby/soft/install_path/envs/syri/lib/python3.5/site-packages/scipy/_lib/_uarray/__init__.py", line 114, in <module>
    from ._backend import *
  File "/home/zhuby/soft/install_path/envs/syri/lib/python3.5/site-packages/scipy/_lib/_uarray/_backend.py", line 1, in <module>
    from typing import (
ImportError: cannot import name 'Type'

I try to install typing using "conda install" and "pip install", but it doesn't work.
python == 3.5.1, the other modules as list:
biopython==1.76
certifi==2018.8.24
cycler==0.10.0
Cython==0.29.21
kiwisolver==1.1.0
matplotlib==3.0.0
numpy==1.18.5
pandas==0.23.4
psutil==5.8.0
pycairo==1.17.1
pyparsing==2.4.7
pysam==0.16.0.1
python-dateutil==2.8.1
python-igraph==0.7.1.post6
pytz==2021.1
scipy==1.4.1
six==1.15.0
syri==1.4
texttable==1.6.3
tornado==5.1.1
typing==3.7.4.3
Looking forward to your reply!

**Comment by zbyxinalice03** [comment]
Hi:
I have solve this issue, my scipyversion is 1.4.1, and I install a version 1.2.1, It wokrs.
