### ISSUE TITLE
chroder

### ISSUE THREAD

**Issue by PhDstuff** [schneebergerlab/syri#8]
Hello, 
When using chroder, 
I come across this issue:
```

Traceback (most recent call last):
  File "../../../syri-master/syri/bin/chroder", line 716, in <module>
    scaf(args)
  File "../../../syri-master/syri/bin/chroder", line 337, in scaf
    refdata = getdata(reflength, refid, refdir)
  File "../../../syri-master/syri/bin/chroder", line 78, in getdata
    fnd = defaultdict(dict)
NameError: name 'defaultdict' is not defined
```

**Comment by mnshgl0110** [comment]
This bug should be fixed now.
