### ISSUE TITLE
How to deal with the question when I ran the SyRi 

### ISSUE THREAD

**Issue by pengyan19** [schneebergerlab/syri#89]
Reading Coords - ERROR - chr19 in genome B is best match for two chromosomes in genome A.Cannot assign chromosomes automatically.

**Comment by mnshgl0110** [comment]
SyRI analyses homologous chromosomes between the two genomes. For this it uses chromosome IDs, assuming that homologous chromosomes would have same chromosome IDs. If the chromosome IDs are not same exactly same in the two assemblies, then, SyRI tries to find homologous chromosomes based on alignment. Here, chr19 in query genome appears to be homologous to two query genome, so SyRI cannot decide which of the two is the actual homologous chromosome.

You can solve this problem by ensuring that homologous chromosomes have exactly the same chromosome ID. Also, only analyse chromosomes and remove contigs/scaffolds from the assembly.

**Comment by pengyan19** [comment]
Hi,you suggest that I need to  change the chr19 name in the query genome according to the reference genome chromosome id. Right?

**Comment by mnshgl0110** [comment]
Yes, that would be the best strategy. But, you would need to do this for all chromosomes. That is, for each chromosome in reference genome, you assign the same chromosome ID to the homologous chromosome in query genome. Also, filter out unplaced contigs/scaffolds.

**Comment by pengyan19** [comment]
I have met a new question which are present as follows:
 multiprocessing.pool.RemoteTraceback: 
"""
 Traceback (most recent call last):
  File "/public/home/pengyan/anaconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 119, in worker
 result = (True, func(*args, **kwds))
 File "/public/home/pengyan/anaconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 754, in syri.pyxFiles.synsearchFunctions.syri
 IndexError: list index out of range
 """

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "/public/home/pengyan/biosoft/syri/syri/bin/syri", line 250, in <module>
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
   File "syri/pyxFiles/synsearchFunctions.pyx", line 456, in syri.pyxFiles.synsearchFunctions.startSyri
   File "syri/pyxFiles/synsearchFunctions.pyx", line 457, in syri.pyxFiles.synsearchFunctions.startSyri
  File "/public/home/pengyan/anaconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/public/home/pengyan/anaconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 644, in get
   raise self._value
 IndexError: list index out of range
(END)

**Comment by mnshgl0110** [comment]
Check this: https://github.com/schneebergerlab/syri/issues/48
