### ISSUE TITLE
Error Running SYRI - IndexError: list index out of range

### ISSUE THREAD

**Issue by aamirwkhan06** [schneebergerlab/syri#95]
Hi Manish,

I am aligning two plant genomes using minimap2 and giving the output SAM files as input to SYRI. I have a set of such genomes to be compared with one of the reference genomes. For some genomes, it runs fine and gives the VCF and other output files - with no errors. However, for some genomes I am getting the following error:

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Programs/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Programs/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 754, in syri.pyxFiles.synsearchFunctions.syri
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Programs/syri/syri/bin/syri", line 252, in <module>
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 456, in syri.pyxFiles.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 457, in syri.pyxFiles.synsearchFunctions.startSyri
  File "/Programs/anaconda3/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Programs/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range

I am running SYRI 1.5 and using the following minimap command to generate the whole genome alignments:

/Programs/minimap2-2.22_x64-linux/minimap2 -ax asm5 -t 60 --eqx Ref.genome.fasta Query.genome.fasta > Ref_Query_asm5.sam

Could you please suggest what the issue might be which is resulting in this error?

Please ignore the PATH of the scripts or commands, as I have pasted the modified ones.

Thank you.

Best,
Aamir

**Comment by HongboTang** [comment]
Hello, do I need to reverse the sequence or reverse complementation?Thank you very much!

**Comment by HongboTang** [comment]
Hello, do I need to reverse the sequence or reverse complementation?Thank you very much! @mnshgl0110

**Comment by mnshgl0110** [comment]
Reverse complement, but make sure that same strands are being compared in both genomes.
